### ISSUE TITLE
(node:30287) UnhandledPromiseRejectionWarning: Error: No accounts for this token

### ISSUE THREAD

**Issue by smatiush** [blockworks-foundation/liquidator#1]
hi,  i'm testing the code but on the sturtup after yarn  partialLiquidate, this error has been printed,

`yarn run v1.22.10
$ ts-node src/partial.ts
(node:30287) UnhandledPromiseRejectionWarning: Error: No accounts for this token
    at Object.findLargestTokenAccountForOwner (/home/cg/Desktop/pmsr/defi/solana_liquidetor3000/liquidator-main/node_modules/@blockworks-foundation/mango-client/src/utils.ts:295:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:30287) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30287) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 7.77s.`

can be a problem with my .env file? 
here it is:

'export CLUSTER="mainnet-beta"
export CLUSTER_URL="https://solana-api.projectserum.com"
export KEYPAIR=~/.config/solana/id.json
export NODE_ENV=production
export TARGETS="0.0002 0.006"
export GROUP_NAME="BTC_ETH_USDT"
export CHECK_INTERVAL="1000.0" '

**Comment by soapyp** [comment]
Your env file looks fine @smatiush, do you have spl-token accounts associated with that keypair for ETH, BTC, and Native USDT? You can check the mainnet public keys for the tokens here: https://github.com/blockworks-foundation/mango-client-ts/blob/main/src/ids.json#L186

**Comment by smatiush** [comment]
thanks for the answer, but i have already checked it, if i try via the ui i can trade normally with the same address of the keypair.

**Comment by smatiush** [comment]
do i need a minimum amount in my wallet?

**Comment by OpinionatedGeek** [comment]
You can try using the [AccountScout](https://mybinder.org/v2/gl/OpinionatedGeek%2Fmango-explorer/HEAD?filepath=AccountScout.ipynb) I wrote to report on problems with Mango margin accounts. If you go to that page (and wait a long time for it to load) you can enter your root PublicKey and generate a report of errors and warnings, along with details of sub-accounts.

(If it turns out that it says your account is OK but later there turns out to be a problem like a missing sub-account, please let me know and I'll add it to the list of checks.)

**Comment by smatiush** [comment]
thx @OpinionatedGeek and @riordanp  i have found the problem, my keypair was wrong in .env file

**Comment by smatiush** [comment]
but now this appear to me:
![image](https://user-images.githubusercontent.com/24374501/116120529-e8d26900-a6bf-11eb-8400-884a4dcbe270.png)

some help?
